### ISSUE TITLE
Built Image has issues

### ISSUE THREAD

**Issue by ProbablePrime** [Yellow-Dog-Man/go.resonite.com#4]
Now that we have an image, I wanted to avoid git pulling the source code down to the host machine.

So i setup a new folder and docker-compose that doesn't have any of the contents of this repository within it:
```
version: '3.8'
services:
  app:
    image: "ghcr.io/yellow-dog-man/go.resonite.com:main"
    container_name: go.cheese.com
    ports:
      - "3003:3000"
    expose:
      - "3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=production
```

running docker compose up on this file, leads to a stopped container with:
```
npm error code ENOENT
npm error syscall open
npm error path /usr/src/app/package.json
npm error errno -2
npm error enoent Could not read package.json: Error: ENOENT: no such file or directory, open '/usr/src/app/package.json'
npm error enoent This is related to npm not being able to find a file.
npm error enoent
npm error A complete log of this run can be found in: /root/.npm/_logs/2024-11-15T09_17_54_081Z-debug-0.log
```

This points to an error in my Dockefile but Im not sure what.

@jae1911 Do you have ideas?
